FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

WORKDIR /usr/src/app/

COPY Pipfile Pipfile.lock /usr/src/app/
RUN pip install pipenv && pipenv install --system

COPY . /usr/src/app/

CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
